/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;


import Person.Student;
import model.DB4OUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Classroom;
import model.DayCare;


public class AddStudentToGroupDialog extends javax.swing.JDialog {
    DayCare daycare;
    ClassRoomsView cview;
    DB4OUtil db40Util = DB4OUtil.getInstance();
    Classroom classroom;
    /**
     * Creates new form AddStudentToGroupDialog
     */
    public AddStudentToGroupDialog(DayCare daycare, ClassRoomsView cview, Classroom classroom) {
        this.daycare = daycare;
        this.cview = cview;
        this.classroom = classroom;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectStudentLabel = new javax.swing.JLabel();
        confirmAddToGroup = new javax.swing.JButton();
        selectStudentInput = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        selectStudentLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        selectStudentLabel.setText("Please Select Student：");

        confirmAddToGroup.setBackground(new java.awt.Color(255, 153, 0));
        confirmAddToGroup.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        confirmAddToGroup.setForeground(new java.awt.Color(255, 255, 255));
        confirmAddToGroup.setText("Confirm");
        confirmAddToGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddToGroupActionPerformed(evt);
            }
        });

        selectStudentInput.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        selectStudentInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectStudentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectStudentInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectStudentInput, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmAddToGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(selectStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(selectStudentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(confirmAddToGroup)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectStudentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStudentInputActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String name = (String)cb.getSelectedItem();
        cb.setSelectedItem(name);
        cview.populateStudentTable();
    }//GEN-LAST:event_selectStudentInputActionPerformed

    private void confirmAddToGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddToGroupActionPerformed
        int studentName = selectStudentInput.getSelectedIndex();
        Student s = daycare.getStudentsList().get(studentName);
        daycare.getClassRoomsList().get(cview.selectedClassIndex).getGroups().get(cview.selectedGroupIndex).getStudentList().add(s);
        cview.populateStudentTable();
        cview.checkMaxLimitForGroup();
        JOptionPane.showMessageDialog(this, "Added Student Successfully");
        ClassRoomsView.handlePostClassroomCreate(this);
        db40Util.storeSystem(daycare);
    }//GEN-LAST:event_confirmAddToGroupActionPerformed

    public void setStudentsDropDown(){
        Vector<Student> students = daycare.getStudentsList();
        int n = students.size();
        String[] options = new String[n];
        int p=0;
        for(int i = 0; i< n; i++){
            if(this.classroom.getAgeLower()<=students.get(i).getAge() && students.get(i).getAge()<this.classroom.getAgeHigher()){
            
                options[p++] = students.get(i).getFirstName()+" "+students.get(i).getLastName();
            }
        }
        selectStudentInput.setModel(new javax.swing.DefaultComboBoxModel<>(options));
    }

    public void postInit(){
        setStudentsDropDown();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmAddToGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectStudentInput;
    private javax.swing.JLabel selectStudentLabel;
    // End of variables declaration//GEN-END:variables
}
