/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import Person.Teacher;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;


public class AddTeacherDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddTeacherDialog
     */
    private Vector<Teacher> teachersList;
    public AddTeacherDialog( Vector<Teacher> teachersList) {
        //super(parent, modal);
        initComponents();
        this.teachersList = teachersList;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblGpa = new javax.swing.JLabel();
        txtCredits = new javax.swing.JTextField();
        btnAddTeacher = new javax.swing.JButton();
        lblGpa1 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 153, 30));

        lblName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblName.setText("First Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 95, 16));
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 153, 30));

        lblAge.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblAge.setText("Age (Years)");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 153, 30));

        lblGpa.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblGpa.setText("Review Date");
        jPanel1.add(lblGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        jPanel1.add(txtCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 153, 29));

        btnAddTeacher.setBackground(new java.awt.Color(255, 153, 0));
        btnAddTeacher.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnAddTeacher.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 153, 30));

        lblGpa1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblGpa1.setText("Credits");
        jPanel1.add(lblGpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jDateChooser2.setDateFormatString("y/M/d");
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/teacher.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed

        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String age = txtAge.getText();
        String credits = txtCredits.getText();
        Date date = jDateChooser2.getDate();

        if(firstName.isEmpty() || lastName.isEmpty() || age.isEmpty() || credits.isEmpty() )
        {
            String message = "One or more fields or missing. Please Check";
            JOptionPane.showMessageDialog(this, "Missing Fields", message, 2);
            return;
        }
        
        int intAge = Integer.parseInt(age);
        int intCredits = Integer.parseInt(credits);
        Teacher teacher = new Teacher(firstName, lastName,intAge, intCredits, date);
        teachersList.add(teacher);
        JOptionPane.showMessageDialog(this, "Added Successfully", "Added Student", 1);
        dispose();

    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    public void clearFields()
    {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtCredits.setText("");
      
   }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeacher;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JLabel lblGpa1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
