/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;



import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Classroom;
import model.DB4OUtil;
import model.DayCare;
import util.UiUtil;


public class ClassRoomDialog extends javax.swing.JDialog {
    DayCare dayCare;
    ClassRoomsView cv;
    DB4OUtil db4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form AddClassRoomDialog
     */
    public ClassRoomDialog(DayCare daycare, ClassRoomsView cv) {
        this.dayCare= daycare;
        this.cv = cv;
        initComponents();
        postInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ageFromLabel = new javax.swing.JLabel();
        confirmAddClassroom = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        ageGroupSelect = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        classRoomName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ageFromLabel.setBackground(new java.awt.Color(255, 102, 0));
        ageFromLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        ageFromLabel.setText("Age range:");
        jPanel1.add(ageFromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 25));

        confirmAddClassroom.setBackground(new java.awt.Color(255, 102, 0));
        confirmAddClassroom.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        confirmAddClassroom.setForeground(new java.awt.Color(255, 255, 255));
        confirmAddClassroom.setText("Confirm");
        confirmAddClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddClassroomActionPerformed(evt);
            }
        });
        jPanel1.add(confirmAddClassroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 295, 140, 40));

        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("Only number fields are allowed");
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        ageGroupSelect.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        ageGroupSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ageGroupSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageGroupSelectActionPerformed(evt);
            }
        });
        jPanel1.add(ageGroupSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 183, 156, 40));

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, -1));

        classRoomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRoomNameActionPerformed(evt);
            }
        });
        jPanel1.add(classRoomName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 156, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddClassroomActionPerformed
        try{
            String ageGroup = (String) ageGroupSelect.getSelectedItem();
            String[] groupDes = ageGroup.split("-");
            int ageLower = Integer.parseInt(groupDes[0]);
            int ageHigher = Integer.parseInt(groupDes[1]);
            int groupSize = UiUtil.maxGroups[ageGroupSelect.getSelectedIndex()];
            String name = classRoomName.getText();
            JOptionPane.showMessageDialog(this, "Classroom added successfully");
            Classroom c = new Classroom(ageLower, ageHigher, groupSize, name);
            dayCare.getClassRoomsList().add(c);
            db4OUtil.storeSystem(dayCare);
            ClassRoomsView.handlePostClassroomCreate(this);
            cv.setClassRoomDropDown(dayCare.getClassRoomsList());
            if(dayCare.getClassRoomsList().size()==1){
                cv.setDefaultClassRoom();
            }
            
        }catch(NumberFormatException e){
            errorLabel.setVisible(true);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_confirmAddClassroomActionPerformed

    private void ageGroupSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageGroupSelectActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String name = (String)cb.getSelectedItem();
        cb.setSelectedItem(name);        // TODO add your handling code here:
    }//GEN-LAST:event_ageGroupSelectActionPerformed

    private void classRoomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRoomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classRoomNameActionPerformed

 
    public void postInit(){
        errorLabel.setVisible(false);
        setAgeGroups();
    }
    
    public void setAgeGroups(){
        String[] classOptions = UiUtil.ageGroups;
        int n = classOptions.length;
        String[] options = new String[n];
        for(int i = 0; i< n; i++){
            options[i] = classOptions[i];
        }
        ageGroupSelect.setModel(new javax.swing.DefaultComboBoxModel<>(options));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageFromLabel;
    private javax.swing.JComboBox<String> ageGroupSelect;
    private javax.swing.JTextField classRoomName;
    private javax.swing.JButton confirmAddClassroom;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
