/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;


import Person.Student;
import Person.Teacher;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Classroom;
import model.DayCare;
import model.Group;
import util.GroupRules;


public class ClassRoomsView extends javax.swing.JPanel {

    Vector<Object> classRooms = new Vector<>();
    DefaultTableModel groupDtm;
    DefaultTableModel studentDtm;
    DayCare daycare;
    int selectedGroupIndex;
    int selectedClassIndex;
    /**
     * Creates new form ClassRoomsView
     */
    public ClassRoomsView(DayCare daycare) {
        this.daycare = daycare;
        selectedGroupIndex = -1;
        selectedClassIndex = -1;
        initComponents();
        postInit(daycare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectClassroomPanel = new javax.swing.JPanel();
        totalCount = new javax.swing.JLabel();
        addTeacherButton = new javax.swing.JButton();
        classRoomSelect = new javax.swing.JComboBox<>();
        selectGroupPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupsTable = new javax.swing.JTable();
        groupsLabel = new javax.swing.JLabel();
        addGroupButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        groupLimitLabel = new javax.swing.JLabel();
        groupInfoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        notePrefix = new javax.swing.JLabel();
        noteValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addStudentToGroupButton = new javax.swing.JButton();
        teacherLabel = new javax.swing.JLabel();
        teacherValueLabel = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setText("PLEASE SELECT A CLASSROOM:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(286, 286, 286))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 868, -1));

        selectClassroomPanel.setBackground(new java.awt.Color(255, 255, 255));

        addTeacherButton.setBackground(new java.awt.Color(255, 102, 0));
        addTeacherButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        addTeacherButton.setForeground(new java.awt.Color(255, 255, 255));
        addTeacherButton.setText("+ Add");
        addTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherButtonActionPerformed(evt);
            }
        });

        classRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        classRoomSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classRoomSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectClassroomPanelLayout = new javax.swing.GroupLayout(selectClassroomPanel);
        selectClassroomPanel.setLayout(selectClassroomPanelLayout);
        selectClassroomPanelLayout.setHorizontalGroup(
            selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(classRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(totalCount)
                    .addContainerGap(824, Short.MAX_VALUE)))
        );
        selectClassroomPanelLayout.setVerticalGroup(
            selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classRoomSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(selectClassroomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectClassroomPanelLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(totalCount)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        add(selectClassroomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 868, -1));

        selectGroupPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        groupsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        groupsTable.setColumnSelectionAllowed(true);
        groupsTable.getTableHeader().setReorderingAllowed(false);
        groupsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(groupsTable);
        groupsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        groupsLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        groupsLabel.setText("Groups:");

        addGroupButton.setBackground(new java.awt.Color(255, 102, 0));
        addGroupButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        addGroupButton.setForeground(new java.awt.Color(255, 255, 255));
        addGroupButton.setText("+ Add");
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Group limit for this class: ");

        javax.swing.GroupLayout selectGroupPanelLayout = new javax.swing.GroupLayout(selectGroupPanel);
        selectGroupPanel.setLayout(selectGroupPanelLayout);
        selectGroupPanelLayout.setHorizontalGroup(
            selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(selectGroupPanelLayout.createSequentialGroup()
                            .addComponent(groupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addGroupButton))
                        .addGroup(selectGroupPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(groupLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        selectGroupPanelLayout.setVerticalGroup(
            selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectGroupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupsLabel)
                    .addComponent(addGroupButton))
                .addGap(18, 18, 18)
                .addGroup(selectGroupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(groupLimitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        add(selectGroupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 223, -1, -1));

        groupInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        groupInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Age", "Contact Phone No."
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        groupInfoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, 298));

        notePrefix.setForeground(new java.awt.Color(255, 51, 51));
        notePrefix.setText("Note: Maximum number of students allowed:");
        groupInfoPanel.add(notePrefix, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        noteValue.setText("-1");
        groupInfoPanel.add(noteValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 53, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setText("Students");
        groupInfoPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        addStudentToGroupButton.setBackground(new java.awt.Color(255, 102, 0));
        addStudentToGroupButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        addStudentToGroupButton.setForeground(new java.awt.Color(255, 255, 255));
        addStudentToGroupButton.setText("+ Add");
        addStudentToGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentToGroupButtonActionPerformed(evt);
            }
        });
        groupInfoPanel.add(addStudentToGroupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        teacherLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        teacherLabel.setForeground(new java.awt.Color(255, 51, 51));
        teacherLabel.setText("Teacher: ");
        groupInfoPanel.add(teacherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 66, 31));

        teacherValueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        groupInfoPanel.add(teacherValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, 250, 31));

        add(groupInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 223, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherButtonActionPerformed
        ClassRoomDialog addClass = new ClassRoomDialog(daycare, this);
        addClass.setLocationRelativeTo(null);
        addClass.setVisible(true);
    }//GEN-LAST:event_addTeacherButtonActionPerformed

    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        GroupDialog ag = new GroupDialog(daycare, classRoomSelect.getSelectedIndex(), this);
        ag.setLocationRelativeTo(null);
        ag.setVisible(true);
    }//GEN-LAST:event_addGroupButtonActionPerformed

    private void classRoomSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classRoomSelectActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        String name = (String)cb.getSelectedItem();
       
        int index = cb.getSelectedIndex();
        if(index > -1){
            cb.setSelectedIndex(cb.getSelectedIndex());
            populateGroupTable();
            selectGroupPanel.setVisible(true);
            cb.setSelectedItem(name);
            selectedClassIndex = index;
            groupLimitLabel.setText(""+daycare.getClassRoomsList().get(cb.getSelectedIndex()).getMaxGroup());
            
        }
        checkMaxLimitForGroup();
        checkMaxLimitForGroupAddition();
        
    }//GEN-LAST:event_classRoomSelectActionPerformed

    private void groupsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsTableMouseClicked
            JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            String s=source.getModel().getValueAt(row, 0)+"";
            groupInfoPanel.setVisible(true);
            selectedGroupIndex = row;
            noteValue.setText(""+daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex()).getGroups().get(row).getGroupSize());
            checkMaxLimitForGroup();
            populateStudentTable();
            setTeacherName();
    }//GEN-LAST:event_groupsTableMouseClicked

    private void addStudentToGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentToGroupButtonActionPerformed
        AddStudentToGroupDialog as = new AddStudentToGroupDialog(daycare, this);
        as.setLocationRelativeTo(null);
        as.setVisible(true);
    }//GEN-LAST:event_addStudentToGroupButtonActionPerformed
    public void postInit(DayCare daycare){
        classRoomSelect.setSelectedItem(null);
        selectGroupPanel.setVisible(false);
        groupInfoPanel.setVisible(false);
        setClassRoomDropDown(daycare.getClassRoomsList());
        classRoomSelect.setSelectedItem(null);
        groupDtm = (DefaultTableModel) groupsTable.getModel();
        studentDtm = (DefaultTableModel) studentTable.getModel();
        checkMaxLimitForGroup();
    }
    
    public void setDefaultClassRoom(){
        classRoomSelect.setSelectedItem(null);
    }
    
    public void setClassRoomDropDown(Vector<Classroom> classRooms){
        int n = classRooms.size();
        System.out.println(n);
        String[] options = new String[n];
        for(int i = 0; i< n; i++){
            options[i] = (String) classRooms.get(i).getName();
        }
        classRoomSelect.setModel(new javax.swing.DefaultComboBoxModel<>(options));
    }
            
    
    public static void handlePostClassroomCreate (JDialog jd){
        jd.dispose();
    }
    public static void handlePostStudentAddition (JDialog jd, int limit){
        jd.dispose();
        
    }
    
    public void checkMaxLimitForGroup(){
        if(selectedGroupIndex>=0){
        int sizeLimit = Integer.parseInt(noteValue.getText());
        int actualSize = daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex()).getGroups().get(selectedGroupIndex).getStudentList().size();
        if(actualSize>=sizeLimit){
            addStudentToGroupButton.setVisible(false);
        }
        else{
            addStudentToGroupButton.setVisible(true);
        }
        }
    }
    
    public void checkMaxLimitForGroupAddition(){
        if(selectedClassIndex>=0){
            Classroom c = daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex());
            boolean b = GroupRules.validate(c.getAgeLower(), c.getAgeHigher(), c.getGroups().size());
            addGroupButton.setVisible(b);
    }
    }  
    public void populateGroupTable(){
        Classroom c = daycare.getClassRoomsList().get(classRoomSelect.getSelectedIndex());
        Vector<Group> groups = c.getGroups();
        int n = groups.size();
        String[] options = new String[n];
        groupDtm.setRowCount(0);
        
        for ( Group p : groups)
        {
         
             groupDtm.addRow(new Object[]{ p.getGroupName()});
        }
        groupsTable.setModel(groupDtm);
    }
    
    public void populateStudentTable(){
        studentTable.setVisible(false);
        Vector<Student> students = daycare.getClassRoomsList().get(selectedClassIndex).getGroups().get(selectedGroupIndex).getStudentList();
  
        int n = students.size();
        String[] options = new String[n];
        studentDtm.setRowCount(0);
        int x = 0;
        for ( Student p : students)
        {
         
             studentDtm.addRow(new Object[]{++x, p.getFirstName(), p.getLastName(), p.getAge(), String.valueOf(p.getPhoneNumber())});
        }
        studentTable.setModel(studentDtm);
        studentTable.setVisible(true);
    }
    
    public void setTeacherName(){
        Teacher t = daycare.getClassRoomsList().get(selectedClassIndex).getGroups().get(selectedGroupIndex).getTeacher();
        teacherValueLabel.setText(""+t.getFirstName()+" "+t.getLastName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addStudentToGroupButton;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JComboBox<String> classRoomSelect;
    private javax.swing.JPanel groupInfoPanel;
    private javax.swing.JLabel groupLimitLabel;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JTable groupsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel notePrefix;
    private javax.swing.JLabel noteValue;
    private javax.swing.JPanel selectClassroomPanel;
    private javax.swing.JPanel selectGroupPanel;
    private javax.swing.JTable studentTable;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JLabel teacherValueLabel;
    private javax.swing.JLabel totalCount;
    // End of variables declaration//GEN-END:variables
}
