package UI;

import Person.Student;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;



public class StudentDialog extends javax.swing.JDialog {

 
    public StudentDialog(Vector<Student> studentsList) 
            
    {    //super(parent, modal);
        initComponents();
        lblPhoneWarning.setVisible(false);
        lblValid.setVisible(false);
        this.studentsList = studentsList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        lblGpa = new javax.swing.JLabel();
        lblFatherName = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhoneNum = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        lblPhoneWarning = new javax.swing.JLabel();
        lblValid = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        lblMotherName = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblGpa1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Add New Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 190, -1));

        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 234, 40));

        lblName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("First Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblLastName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name");
        jPanel1.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 212, -1, -1));

        txtLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 234, 40));

        lblAge.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAge.setText("Age");
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 289, -1, -1));

        txtAge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, 234, 37));

        txtGpa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGpaActionPerformed(evt);
            }
        });
        jPanel1.add(txtGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 400, 234, 40));

        lblGpa.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblGpa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGpa.setText("Weight");
        jPanel1.add(lblGpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 375, -1, -1));

        lblFatherName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblFatherName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFatherName.setText("Father Name");
        jPanel1.add(lblFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 131, -1, -1));

        txtFatherName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 234, 40));

        lblAddress.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblAddress.setText("Address");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 289, -1, -1));
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 320, 234, 35));

        lblPhoneNum.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblPhoneNum.setText("Contact Phone No.");
        jPanel1.add(lblPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 375, -1, -1));

        txtPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneNumKeyReleased(evt);
            }
        });
        jPanel1.add(txtPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 399, 234, 40));

        lblPhoneWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblPhoneWarning.setText("Invalid Phone Number");
        jPanel1.add(lblPhoneWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 453, -1, -1));
        jPanel1.add(lblValid, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 408, 46, 39));

        btnAddStudent.setBackground(new java.awt.Color(255, 102, 0));
        btnAddStudent.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 480, 234, 40));

        lblMotherName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblMotherName.setText("Mother Name");
        jPanel1.add(lblMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 212, -1, -1));
        jPanel1.add(txtMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 243, 234, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/children.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 6, -1, 98));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 476, 234, 44));

        lblGpa1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblGpa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGpa1.setText("Registeration Date");
        jPanel1.add(lblGpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 451, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed

        String firstName = txtName.getText();
        String lastName = txtLastName.getText();
        String age = txtAge.getText();
        String gpa = txtGpa.getText();
        String fatherName = txtFatherName.getText();
        String motherName = txtMotherName.getText();
        String address = txtAddress.getText();
        String phoneNumber = txtPhoneNum.getText();

        Date date = jDateChooser1.getDate();
        if(firstName.isEmpty() || lastName.isEmpty() || age.isEmpty() || gpa.isEmpty() || fatherName.isEmpty() || motherName.isEmpty()||address.isEmpty() || phoneNumber.isEmpty())
        {
            String message = "One or more fields or missing. Please Check";
            JOptionPane.showMessageDialog(this, "Missing Fields", message, 2);
            return;
        }

        if ( !phoneNumber.matches("\\d{10}") )
        {
            String message = "Please enter a valid Phone number";
            JOptionPane.showMessageDialog(this, message, "Invalid Phone Number", 2);
            return;
        }

        int intAge = Integer.parseInt(age);
        Double doubleGpa = Double.parseDouble(gpa);
        Student student = new Student(firstName,lastName, intAge, doubleGpa, fatherName, motherName, address,phoneNumber,  date);
        studentsList.add(student);
        JOptionPane.showMessageDialog(this, "Added Student Successfully..!", "Added Student", 1);
        dispose();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void txtPhoneNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumKeyReleased
        if(! txtPhoneNum.getText().matches("\\d{10}"))
        {
            lblPhoneWarning.setVisible(true);
            lblValid.setVisible(false);
        }
        else{
            lblPhoneWarning.setVisible(false);
            lblValid.setVisible(true);
        }
    }//GEN-LAST:event_txtPhoneNumKeyReleased

    private void txtGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGpaActionPerformed


    private Vector<Student> studentsList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFatherName;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JLabel lblGpa1;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMotherName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPhoneWarning;
    private javax.swing.JLabel lblValid;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNum;
    // End of variables declaration//GEN-END:variables
}
