/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Person.Teacher;

import java.awt.Dialog;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.DateUtil;
import util.FileUtil;


public class TeachersView extends javax.swing.JPanel {

    /**
     * Creates new form Teachers
     */
    DefaultTableModel myTM;
    private Vector<Teacher> teachersList;
    public TeachersView(Vector<Teacher> teachersList) {
        initComponents();
        this.teachersList = teachersList;
        postInit();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();
        totalCount = new javax.swing.JLabel();
        totalCountLabel = new javax.swing.JLabel();
        addTeacherThroughCSVButton = new javax.swing.JButton();
        addTeacherThroughFormButton = new javax.swing.JButton();
        teacherHeadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 722, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        teacherTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "First Name", "Last Name", "Age", "Credits", "Review Date"
            }
        ));
        jScrollPane1.setViewportView(teacherTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 760, 240));
        add(totalCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 48, 36));

        totalCountLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalCountLabel.setForeground(new java.awt.Color(204, 153, 0));
        totalCountLabel.setText("Total count:");
        add(totalCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        addTeacherThroughCSVButton.setBackground(new java.awt.Color(255, 153, 0));
        addTeacherThroughCSVButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        addTeacherThroughCSVButton.setForeground(new java.awt.Color(255, 255, 255));
        addTeacherThroughCSVButton.setText("Add By CSV File ");
        addTeacherThroughCSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherThroughCSVButtonActionPerformed(evt);
            }
        });
        add(addTeacherThroughCSVButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 160, 40));

        addTeacherThroughFormButton.setBackground(new java.awt.Color(255, 153, 0));
        addTeacherThroughFormButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        addTeacherThroughFormButton.setForeground(new java.awt.Color(255, 255, 255));
        addTeacherThroughFormButton.setText("Add By Form");
        addTeacherThroughFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherThroughFormButtonActionPerformed(evt);
            }
        });
        add(addTeacherThroughFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 140, 40));

        teacherHeadingLabel.setFont(new java.awt.Font("PT Sans", 0, 24)); // NOI18N
        teacherHeadingLabel.setText("T E A C H E R S");
        add(teacherHeadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 256, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/teacher.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addTeacherThroughCSVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherThroughCSVButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("./"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            if(selectedFile.getAbsolutePath().endsWith(".csv"))
            {
                 List<String> csvStrings = FileUtil.readCSVFile( selectedFile.getAbsolutePath());
                 for(String csvString : csvStrings)
                     teachersList.add(new Teacher(csvString));
                 
                 JOptionPane.showMessageDialog(this, "Added Successfully!", "Added Teachers", 1);
                  populateTable();
                  updateTotalCount();
                  jPanel2.setVisible(false); 
            }
            else{
               
                JOptionPane.showMessageDialog(this, "Please select csv files only", "CSV file required ", 2);
            }
        }
    }//GEN-LAST:event_addTeacherThroughCSVButtonActionPerformed

    private void addTeacherThroughFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherThroughFormButtonActionPerformed
         try 
         {
            AddTeacherDialog dialog = new AddTeacherDialog(teachersList);
            dialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        populateTable();
        updateTotalCount();
        jPanel2.setVisible(false); 
    }//GEN-LAST:event_addTeacherThroughFormButtonActionPerformed

    public void populateTable()
    {
        
        myTM.setRowCount(0);
        int ix = 0;
        for (Teacher teacher : teachersList) {
         
            String date = DateUtil.parseDateToString(teacher.getReviewDate(), "y/M/d");
            Object[] objs = new Object[] {++ix, teacher.getFirstName(), teacher.getLastName(), teacher.getAge(), teacher.getCredits(), date};
            myTM.addRow(objs);
        }
        
    }
    
    public void updateTotalCount()
    {
        totalCountLabel.setText("Total Count: " + teachersList.size());
    }
    
    public void generateTable(){
        
        myTM = (DefaultTableModel) teacherTable.getModel();
        jScrollPane1.setVisible(false);
        teacherTable.setAutoCreateRowSorter(true);
        teacherTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        teacherTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(teacherTable);
        jScrollPane1.setVisible(true);
        populateTable();
        
    }
    
    public void postInit(){
        jPanel2.setVisible(false); 
        generateTable();
        updateTotalCount();
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeacherThroughCSVButton;
    private javax.swing.JButton addTeacherThroughFormButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel teacherHeadingLabel;
    private javax.swing.JTable teacherTable;
    private javax.swing.JLabel totalCount;
    private javax.swing.JLabel totalCountLabel;
    // End of variables declaration//GEN-END:variables
}
