/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;


import Person.Student;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import util.DateUtil;
import vaccine.Vaccine;
import vaccine.Dose;


public class ViewImmunizationDialog extends javax.swing.JDialog {

    private Student student;
    DefaultTableModel myTM;
    /**
     * Creates new form ViewImmunizationDialog
     */
    public ViewImmunizationDialog(Student student) {
       
        this.student = student;
        initComponents();
        postInit();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineTable = new javax.swing.JTable();
        lblSelectVaccine = new javax.swing.JLabel();
        cbVaccineList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imunization Records");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 153, 0));
        labelTitle.setText("Student Name: <Student Name>     Age: <AGE>");
        jPanel2.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        vaccineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Dose Number", "Date"
            }
        ));
        vaccineTable.setShowGrid(true);
        jScrollPane1.setViewportView(vaccineTable);

        lblSelectVaccine.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblSelectVaccine.setForeground(new java.awt.Color(255, 153, 0));
        lblSelectVaccine.setText("Select Vaccine：");

        cbVaccineList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbVaccineList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVaccineListActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vaccine.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbVaccineList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSelectVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(315, 315, 315))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblSelectVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbVaccineList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVaccineListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVaccineListActionPerformed

        int index = cbVaccineList.getSelectedIndex();
        if(index != -1)
        {
            String slectedItem = cbVaccineList.getSelectedItem().toString();
            populateTable(slectedItem);
        }
        
    }//GEN-LAST:event_cbVaccineListActionPerformed

  
        
    public void postInit()
    {
        generateTable();
        populateLabel();
        populateComboBox();
        
    }
     public void generateTable(){
        
        myTM = (DefaultTableModel) vaccineTable.getModel();
        jScrollPane1.setVisible(false);
        vaccineTable.setAutoCreateRowSorter(true);
        vaccineTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        vaccineTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(vaccineTable);
        jScrollPane1.setVisible(true);   
        
        
}
     
     public void populateTable( String selectedVaccine){
         
        myTM.setRowCount(0);
        //int ix = 0; // use ix as an index, i.e. id for object in table
        for (Vaccine vaccine : student.getVaccineList())
        {
           
            String vaccineName = vaccine.getVaccineName();
            if(selectedVaccine.equalsIgnoreCase("all") || vaccineName.equalsIgnoreCase(selectedVaccine)){
                for(Dose dose : vaccine.getDoseDetails())
                {
                    String date = DateUtil.parseDateToString(dose.getDate(), "yyyy-mm-dd");
                     Object[] studentObj = {vaccineName, dose.getDoseNumber(), date};
                     myTM.addRow(studentObj);

                }  
            }
        }
     }
     public void populateLabel()
    {
        String labelText = "Name: "+student.getFirstName() + " " + student.getLastName() + ", Age: " + student.getAge();
        
        labelTitle.setText(labelText);
    }
     
     public void populateComboBox()
     {
         cbVaccineList.removeAllItems();
         
         cbVaccineList.addItem("All");
         for(Vaccine vaccine: student.getVaccineList())
         {
             cbVaccineList.addItem(vaccine.getVaccineName());
         }
     }
             

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbVaccineList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lblSelectVaccine;
    private javax.swing.JTable vaccineTable;
    // End of variables declaration//GEN-END:variables
}
